### ISSUE TITLE
specify tmux 1.7 required

### ISSUE THREAD

**Issue by dgreisen** [ddbeck/oraide#8]
1.7 added the `-l` flag. So need to either test for its support or specify in the docs that oraide requires >=tmux 1.7.

**Comment by ddbeck** [comment]
Thank you for this information, @dgreisen. I think noting the tested tmux version(s) should be in the documentation either way and I'll try to get to that in the next day or so.

As for the actual tmux version limitation, were you prevented from using Oraide, or did you upgrade tmux? My inclination is to simply require tmux 1.7 (and provide an informative error message on versions that don't support the flag), but partial support for earlier versions might be a good idea, if upgrading is a major burden.

**Comment by dgreisen** [comment]
I was running ubuntu 12.10. It did not have tmux 1.7 in its repos. I
upgraded to 13.10 and tmux was upgraded to 1.7. I think a nice error
message is more than sufficient.

**Comment by ddbeck** [comment]
I've documented the requirement, and added a warning on import (I think this is a good balance between making the requirements clear, and flexibility in case someone's running a newer version of tmux). I credited you in the version history for this issue, @dgreisen. Thank you!
